site_name: SEAHOWL documentation
docs_dir: source
site_dir: ../build/doc/source
theme:
  name: material
  logo: assets/logo_totalenergies.png
  favicon: assets/logo_totalenergies.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.fold
    - content.tabs.link
    - palette.toggle
    - instant
  palette:
    - scheme: slate
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

plugins:
  - include-markdown
  - search
  - offline
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: false
            docstring_style: google
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            show_if_no_docstring: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            allow_inspection: true
            inherited_members: true
          paths: ["build"]

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - User Guide:
    - Install: INSTALL.md
    - Using package: user-guide/using_package.md
    - Input files:
      - File hierarchy: user-guide/input-files/index.md
      - Main file: user-guide/input-files/main-file.md
      - Turbine file: user-guide/input-files/turbine-file.md
      - Tower file: user-guide/input-files/tower-file.md
      - Blade file: user-guide/input-files/blade-file.md
      - Rna file: user-guide/input-files/rna-file.md
      - Floater file: user-guide/input-files/floater-file.md
      - Environment file: user-guide/input-files/environment-file.md
    - Output files:
      - Generic outputs: user-guide/output-files/output-generic.md
      - Custom outputs: user-guide/output-files/output-custom.md
  - Dev Guide:
    - Contributing: CONTRIBUTING.md
    - Core workflow: dev-guide/core-workflow.md
    - Simulation workflow: dev-guide/sim-workflow.md
  - C++ API: api/cpp/cpp.md
  - Python API:
    - Modules: api/python/modules.md
    - seahowl: api/python/seahowl.md
    - seahowl.core: api/python/core.md
    - seahowl.elasto: api/python/elasto.md
    - seahowl.fluid: api/python/fluid.md
    - seahowl.fluid.aero: api/python/aero.md
    - seahowl.fluid.hydro: api/python/hydro.md
    - seahowl.servo: api/python/servo.md
    - seahowl.env: api/python/env.md
    - seahowl.io: api/python/io.md
  - About:
    - Contributors: CONTRIBUTORS.md
    - Licence: LICENSE.md
